version: "3.8"

service:
  app:
    imgage: sayedtech/nodejs-calculator:1
    container_name: nodejs_calculator
    restart: alaways
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    drive: bridge
