name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Build Docker image
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/nodejs-calculator
          TAG=${{ github.run_number }}
          echo "Building $IMAGE_NAME:$TAG"
          docker build -t $IMAGE_NAME:$TAG .

      - name: Push Docker image
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/nodejs-calculator
          TAG=${{ github.run_number }}
          docker push $IMAGE_NAME:$TAG
